#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

camel:
  springboot:
    # The Camel context name
    name: ModernInvoice

  component:
    servlet:
      mapping:
        contextPath: /fuse/*

mysql:
  service:
    # The name of the service hosting the MySQL database server,
    # can be customized using the 'MYSQL_SERVICE_NAME' env variable to use a different service
    name:     mysql
    # The database to use, can be customized using the 'MYSQL_SERVICE_DATABASE' env variable
    database: sampledb

spring:
  # Spring JDBC configuration
  datasource:
    url:      jdbc:mysql://${${mysql.service.name}.service.host}:${mysql.service.port}/${mysql.service.database}
    username: ${mysql.service.username}
    password: ${mysql.service.password}

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage!
      ddl-auto: update
    show-sql: false

jdg:
  application-name: cache-service
  application-user: cache
  application-password: cache

# The application configuration properties
example:
  generateOrderPeriod: 10s
  processOrderPeriod: 30s
