spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: "0.2"
              memory: 256Mi
            limits:
              cpu: "1.0"
              memory: 256Mi
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            value: ${mysql-service-username}
          - name: MYSQL_SERVICE_PASSWORD
            value: ${mysql-service-password}
          - name: APPLICATION_NAME
            value: ${jdg-application-name}
          - name: APPLICATION_USER
            value: ${jdg-application-user}
          - name: APPLICATION_PASSWORD
            value: ${jdg-application-password}
